SELECT * FROM MARK WHERE MARK > 6 ORDER BY MARK DESC;

SELECT * FROM PAYMENT WHERE AMOUNT > 300 ORDER BY AMOUNT;

SELECT * FROM PAYMENTTYPE ORDER BY NAME;

SELECT * FROM STUDENT ORDER BY NAME DESC;

SELECT T1.*, T2.AMOUNT FROM STUDENT T1 INNER JOIN PAYMENT T2 on T1.ID = T2.STUDENT_ID WHERE AMOUNT > 1000 ORDER BY T1.BIRTHDAY;