ALTER TABLE STUDENT
    ALTER COLUMN BIRTHDAY DATETIME NOT NULL;

ALTER TABLE MARK
    ADD CONSTRAINT CHK_MarkValue CHECK (mark > 0 AND mark < 11);

ALTER TABLE MARK
    ALTER COLUMN subject_id BIGINT NOT NULL;

ALTER TABLE SUBJECT
    ADD CONSTRAINT CHK_GradeValue CHECK (grade > 0 AND grade < 6);

ALTER TABLE PAYMENT
    ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE PAYMENT
    ALTER COLUMN amount DECFLOAT NOT NULL;
ALTER TABLE PAYMENT
    ALTER COLUMN payment_date TIMESTAMP NOT NULL;