SELECT MAX(BIRTHDAY) FROM STUDENT;

SELECT MIN(PAYMENT_DATE) FROM PAYMENT;

SELECT AVG(T1.MARK) FROM MARK T1 INNER JOIN SUBJECT T2 on T2.ID = T1.SUBJECT_ID WHERE T2.NAME = 'Math';

SELECT MIN(T1.AMOUNT) FROM PAYMENT T1 INNER JOIN PAYMENTTYPE T2 on T2.ID = T1.TYPE_ID WHERE T2.NAME = 'WEEKLY';
