CREATE TABLE Student
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45),
    birthday DATE,
    groupnumber INT
);

CREATE TABLE Subject
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250),
    description VARCHAR(255),
    grade INT
);

CREATE TABLE PaymentType
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45)
);

CREATE TABLE Payment
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type_id BIGINT,
    amount DECFLOAT,
    student_id BIGINT,
    payment_date DATETIME,
    FOREIGN KEY(type_id) REFERENCES PAYMENTTYPE(ID),
    FOREIGN KEY(student_id) REFERENCES STUDENT(ID)

);

CREATE TABLE Mark
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT,
    subject_id BIGINT,
    mark INT,
    FOREIGN KEY(student_id) REFERENCES STUDENT(ID),
    FOREIGN KEY(subject_id) REFERENCES SUBJECT(ID)

);
