SELECT T1.STUDENT_ID, AVG(T1.MARK) FROM MARK T1 GROUP BY T1.STUDENT_ID HAVING AVG(T1.MARK) > 8;

SELECT T1.STUDENT_ID, T2.NAME, T1.MARK FROM MARK T1
    INNER JOIN STUDENT T2 on T2.ID = T1.STUDENT_ID
                                       GROUP BY T1.STUDENT_ID, T1.MARK
                                       HAVING MIN(T1.MARK) > 7;

SELECT T1.ID, T1.NAME, COUNT(T2.STUDENT_ID), YEAR(T2.PAYMENT_DATE) FROM STUDENT T1
    INNER JOIN PAYMENT T2 on T1.ID = T2.STUDENT_ID WHERE YEAR(T2.PAYMENT_DATE) = 2019
GROUP BY T1.ID, T1.NAME, YEAR(T2.PAYMENT_DATE)
HAVING COUNT(T2.STUDENT_ID) > 2;


