SELECT T1.ID, T1.NAME, T1.BIRTHDAY, T1.GROUPNUMBER, AVG(T2.MARK) FROM STUDENT T1
    INNER JOIN MARK T2 on T1.ID = T2.STUDENT_ID
GROUP BY T1.ID, T1.NAME, T1.BIRTHDAY, T1.GROUPNUMBER
HAVING AVG(T2.MARK) > 8;

SELECT T1.ID, T1.NAME, MIN(T2.MARK) FROM STUDENT T1
    INNER JOIN MARK T2 on T1.ID = T2.STUDENT_ID
GROUP BY T1.ID, T1.NAME
HAVING MIN(T2.MARK) > 7;

SELECT T1.ID, T1.NAME, COUNT(T2.STUDENT_ID), YEAR(T2.PAYMENT_DATE) FROM STUDENT T1
    INNER JOIN PAYMENT T2 on T1.ID = T2.STUDENT_ID WHERE YEAR(T2.PAYMENT_DATE) = 2019
GROUP BY T1.ID, T1.NAME, YEAR(T2.PAYMENT_DATE)
HAVING COUNT(T2.STUDENT_ID) > 2;


