UPDATE SUBJECT SET GRADE = 5 WHERE NAME = 'End of Suburbia: Oil Depletion and the Collapse of the American Dream';

UPDATE STUDENT SET GROUPNUMBER = 8 WHERE NAME = 'Tremaine Worvill';

SELECT * FROM PAYMENT WHERE PAYMENT_DATE > '2021-01-01' AND TYPE_ID = 2;

UPDATE MARK SET MARK = 2 WHERE STUDENT_ID = 315;