SELECT  T3.ID, T3.NAME, T3.DESCRIPTION, T3.GRADE FROM MARK T2
    INNER JOIN SUBJECT T3 on T3.ID = T2.SUBJECT_ID
                                                 GROUP BY T3.ID, T3.NAME, T3.DESCRIPTION, T3.GRADE
                                                 HAVING AVG(T2.MARK) > (SELECT AVG(T1.MARK) AS AvgMark FROM MARK T1);

SELECT T2.* FROM PAYMENT T2 INNER JOIN STUDENT T3 on T3.ID = T2.STUDENT_ID
            WHERE T2.AMOUNT > (SELECT AVG(T1.AMOUNT) FROM PAYMENT T1)
            ORDER BY T2.ID;